export const getAllUsers = async () => {
  try {
  } catch (error: unknown) {
    // throw error
    console.error('Error getting all users: ', error);
  }
};
